### ISSUE TITLE
No module named 'paho'

### ISSUE THREAD

**Issue by Criswim** [SR42-dev/federated-reinforcement-learning-cartpole#1]
When I run 'python main.py' under the direction 'federatedRLCartpole\rl\rl_main', there was an error occurred
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import rl_utils
  File "C:\Users\xxx\federated-reinforcement-learning-cartpole-main\federated-reinforcement-learning-cartpole-main\federatedRLCartpole\rl\rl_main\rl_utils.py", line 4, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'
Is there anything wrong in the file 'rl_utils.py'? there is no module called 'paho' in my pip list. (I run the code using Windows OS)

**Comment by sr42-dev** [comment]
@freshman-NUDT the module goes by the name 'paho-mqtt', not 'paho'. Give that installation a shot.

I implemented this code on a system running Ubuntu 20.04 while my collaborators were using Windows 11, so I don't think the operating system has any bearing on the usability of the code.

I strongly recommend using a virtual environment for this one. The TensorFlow version mismatch in the original repository this was forked from caused a lot of dependency issues at first, starting with the paho-mqtt package.
